spring.datasource.url=${DB_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:disasterdb}}
spring.datasource.username=${DB_USERNAME:${MYSQLUSER:root}}
spring.datasource.password=${DB_PASSWORD:${MYSQLPASSWORD:}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:${SERVER_PORT:8081}}
